// <auto-generated />
using System;
using Ga.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ga.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Appartenir", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.HasKey("UserId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Appartenirs");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Attendance", b =>
                {
                    b.Property<int>("SeanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Late")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<double>("MissingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValueSql("0.0");

                    b.Property<int?>("ProofId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeanceId", "UserId");

                    b.HasIndex("ProofId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Proof", b =>
                {
                    b.Property<int>("ProofId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Justify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Motive")
                        .HasColumnType("TEXT");

                    b.HasKey("ProofId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Seance", b =>
                {
                    b.Property<int>("SeanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("SeanceId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Appartenir", b =>
                {
                    b.HasOne("GestionDesAbsencesv1.Models.Promotion", "Promotion")
                        .WithMany("Appartenirs")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDesAbsencesv1.Models.User", "User")
                        .WithMany("Appartenirs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Attendance", b =>
                {
                    b.HasOne("GestionDesAbsencesv1.Models.Proof", "Proof")
                        .WithMany("Attendances")
                        .HasForeignKey("ProofId");

                    b.HasOne("GestionDesAbsencesv1.Models.Seance", "Seance")
                        .WithMany("Attendances")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDesAbsencesv1.Models.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proof");

                    b.Navigation("Seance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Seance", b =>
                {
                    b.HasOne("GestionDesAbsencesv1.Models.Classroom", "Classroom")
                        .WithMany("Seances")
                        .HasForeignKey("ClassroomId");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.User", b =>
                {
                    b.HasOne("GestionDesAbsencesv1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Classroom", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Promotion", b =>
                {
                    b.Navigation("Appartenirs");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Proof", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.Seance", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("GestionDesAbsencesv1.Models.User", b =>
                {
                    b.Navigation("Appartenirs");

                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
